#!/bin/bash
set -eu

declare -a merge

merge=( \
  bosh-deployment/bosh.yml \
  # Merge bosh-environmental if bosh is not proto
  -o overlay/operations/bosh-uaa-addons.yml \
  bosh-deployment/uaa.yml \
  bosh-deployment/credhub.yml \
  bosh-deployment/jumpbox-user.yml \
)

# Do features => opsfiles stuff here

for __feature in $GENESIS_REQUESTED_FEATURES; do
  if [[ $__feature =~ bosh-deployment/.* ]] ; then
    if [[ -f "$__feature.yml" ]] ; then
      merge+=( "$__feature.yml" )
    else
      __bail "GENESIS_KIT_NAME/$GENESIS_KIT_VERSION does not support the $__feature feature"
    fi
  elif [[ -f $GENESIS_ROOT/ops/$__feature.yml ]] ; then
    mkdir -p "$(dirname "local_ops/$__feature.yml")"
    cp "$GENESIS_ROOT/ops/$__feature.yml" "local_ops/$__feature.yml"
    merge+=( "local_ops/$__feature.yml" )
  else
    __bail "GENESIS_KIT_NAME/$GENESIS_KIT_VERSION does not support the $__feature feature"
  fi
done

merge+=( \
  # overlay/operations/vault-credhub-proxy.yml \
  # overlay/operations/vault-credhub-proxy-compiled-release.yml \
  # -o bosh-deployment/misc/external-db.yml \
  # -o bosh-deployment/misc/external-db-uaa.yml \
  # -o bosh-deployment/misc/external-db-credhub.yml \
)

echo "${merge[@]}"

